config/routes.rb
Rails.application.routes.draw do
  get "/signout" => "sessions#destroy", as: :destroy_session 
  get "/" => "home#index"
  get "/signup_signin/farmer" => "farmers#new"
  get "/signup_signin/buyer" => "buyers#new"
  get "buy_vegetables/" => "cart_item#new", type: 'Vegetable', as: :vegetable_buy
  get "buy_fruits/" => "cart_item#new", type: 'Fruit', as: :fruits_buy
  get "buy_seeds/" => "cart_item#new", type: 'Seed', as: :seeds_buy

  post "/buy_vegetables/search" => "cart_item#search"
  post "/buy_fruits/search" => "cart_item#search"
  post "/buy_seeds/search" => "cart_item#search"

  delete "/delete_cart_item" => "cart_item#destroy", as: :destroy_cart_item

  resources :farmers, :buyers, :sessions, :cart_item, :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  has_secure_password
  has_many :orders

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base

end

app/models/farmer.rb
class Farmer < ActiveRecord::Base
  has_secure_password
end

app/models/item.rb
class Item < ActiveRecord::Base
    def getVegetables
        where(type: "Vegetable")
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :buyer
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    # [@current_user, @usertype] if @current_user
    # @usertype if @usertype
    puts "in application controllerrrrrrrrrrrrrrrrrrrrr"
    puts session[:current_buyer_id]
    if session[:current_farmer_id]
      @current_user = Farmer.find(session[:current_farmer_id])
      @usertype = "farmer"
      [@current_user, @usertype]
    elsif session[:current_buyer_id]
      @current_user = Buyer.find(session[:current_buyer_id])
      @usertype = "buyer"
      [@current_user, @usertype]
    else
      []
    end
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def new
    @page = "New buyer"
    render "new"
  end

  def index
    lst = current_user
    @buyer = lst[0]
    @usertype = lst[1]
    puts @buyer
    @orders = @buyer.orders
    @page = "Buyer dashboard"
  end

  def create
    name = params[:name]
    email = params[:email]
    password = params[:password]
    address = params[:address]
    phone = params[:phone]

    buyer = Buyer.new(
      name: name,
      email: email,
      password: password,
      address: address,
      phone: phone
    )

    if buyer.save
      flash[:message] = "mew buyer created"
      session[:current_buyer_id] = buyer.id
      redirect_to buyers_path
    else
      flash[:message] = "error while creating buyer"
      redirect_to buyers_path
    end
  end
end

app/controllers/cart_item_controller.rb
class CartItemController < ApplicationController
    
    def index
        lst = current_user
        @current_user = lst[0]
        @items = CartItem.where(buyer_id: @current_user.id)
        @page = "Cart"
    end

    def new
        @page = "New cart item"
        if params.key?(:type)
            if params.key?(:farmer)
                @items = Item.where("itemtype = ? and name = ? and farmer_id = ?", params[:type], params[:item_name], Farmer.where(name: params[:farmer]).ids[0])
            else
                @items = Item.where("itemtype = ?", params[:type])
            end

            lst = current_user
            puts lst.length
            if lst.length == 0
                @current_user_id = ""
            else
                @current_user_id = lst[0].id
            end

            if params[:type] == "Vegetable"
                render "buy_vegetables"
            elsif params[:type] == "Fruit"
                render "buy_fruits"
            elsif params[:type] == "Seed"
                render "buy_seeds"
            else
                redirect_to "/"
            end
            
        else
            redirect_to "/"
        end
    end

    def search
        redirect_to new_cart_item_path(type: params[:itemtype], item_name: params[:item_name], farmer: params[:farmer_name])
    end

    def create
        item = CartItem.new(
            item_id: params[:itemid],
            quantity: params[:quantity],
            buyer_id: params[:buyerid]
        )

        if item.save
            redirect_to cart_item_index_path
        else
            redirect_to "/buy_vegetables"
        end

    end

end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  def new
    @page = "New farmer"
    render "new"
  end

  def index
    @page = "Farmer dashboard"
    lst = current_user
    @farmer = lst[0]
    @usertype = lst[1]
    @vegetables = Item.where("farmer_id= ? and itemtype= ?", @farmer.id, "Vegetable")
    @fruits = Item.where("farmer_id= ? and itemtype= ?", @farmer.id, "Fruit")
    @seeds = Item.where("farmer_id= ? and itemtype= ?", @farmer.id, "Seed")
    @vegetableCount = @vegetables.count
    @fruitCount = @fruits.count
    @seedCount = @seeds.count
  end

  def create
    name = params[:name]
    email = params[:email]
    password = params[:password]
    phone = params[:phone]

    farmer = Farmer.new(
      name: name,
      email: email,
      password: password,
      phone: phone
    )

    if farmer.save
      session[:current_buyer_id] = farmer.id
      redirect_to farmers_path
    else
      flash[:error] = "Error while creating farmer"
      redirect_to farmers_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @page = "Home"
    lst = current_user
    if lst.length == 0
      @current_user = nil
    else
      @current_user = lst[0]
    end
    render "index"
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def new
        @page = "Farmer dashboard"
        current_user
    end

    def create
        current_user
        item = Item.new(
            name: params[:name],
            itemtype: params[:itemtype],
            quantity: params[:quantity],
            price_per_kilo: params[:price_per_kilo],
            farmer_id: @current_user.id
        )

        if item.save
            redirect_to farmers_path
        else
            redirect_to new_item_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if params[:user] == "Farmer"
      farmer = Farmer.find_by(email: params[:email])
      if(farmer && farmer.authenticate(params[:password]))
        session[:current_farmer_id] = farmer.id
        redirect_to farmers_path
      else
        redirect_to new_farmer_path
      end        
    else
      buyer = Buyer.find_by(email: params[:email])
      if(buyer and buyer.authenticate(params[:password]))
        session[:current_buyer_id] = buyer.id
        redirect_to buyers_path
      else
        redirect_to new_buyer_path
      end
    end
  end

  def destroy
    lst = current_user
    puts @usertype
    if @usertype == "buyer"
      session[:current_buyer_id] = nil
      @usertype = nil
    else
      session[:current_farmer_id] = nil
      @usertype = nil
    end

    puts "done #{session[:current_buyer_id]}"
    redirect_to "/"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buyers/_order.html.erb
<div class="order">
    <div class="order-img">

    </div>
    <div class="order-info">
        <div class="order-name">
        Order No : <%= id %>
        </div>
    </div>
</div>

app/views/buyers/index.html.erb
<div class="buyer-dashboard">
    <div class="buyer-info">
        <div class="name">
            <h2><%= @buyer.name %></h2>
        </div>
    </div>


    <div class="orders-container">
        <% if @orders.count == 0 %>
            <div class="no-orders">
                <img src="orders.png" />
                <p>No orders places</p>
            </div>
        <% else %>
            <div class="orders-heading">
                <h3>My Orders</h3>
            </div>
            <div class="main-orders">
                <% for order in @orders %>
                    <%= render partial: "order", locals: {
                        id: order.id
                    } %>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/buyers/new.html.erb
<div class = "signin-signup buyer-forms">
  <div class = "form">
    <div class = "sign-up-form">
      <h3> Sign up </h3>
      <%= form_with url: buyers_path do |form| %>
        <div class = "signup-field">
          <%= form.label :name, "Name" %>
          <%= form.text_field :name %>
        </div>
        
        <div class = "signup-field">
          <%= form.label :email, "Email" %>
          <%= form.email_field :email %>
        </div>

        <div class = "signup-field">
          <%= form.label :password, "Password" %>
          <%= form.password_field :password %>
        </div>

        <div class = "signup-field">
          <%= form.label :address, "Address" %>
          <%= form.text_field :address %>
        </div>
        
        <div class = "signup-field">
          <%= form.label :code, "Phone No." %>
          <%= form.number_field :phone %>
        </div>

        <div class = "signup-field">
          <%= form.submit "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class = "signin-other">
    <div class = "form">
      <div class = "sign-in-form">
        <h3> Sign in </h3>
        <%= form_with url: sessions_path do |form| %>
          <%= form.hidden_field :user, :value => "Buyer"%>

          <div class = "signin-field">
            <label> Email </label>
            <%= form.email_field :email %>
          </div>
      
          <div class = "signin-field">
            <label> Password </label>
            <%= form.password_field :password %>
          </div>
          
          <div class = "signin-field">
            <%= form.submit "Sign in", class: "form-submit" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class = "other-form">
      <%= link_to "Sign up or sign in as Farmer", new_farmer_path %>
    </div>
  </div>
</div>

app/views/cart_item/_buy_fruit.html.erb
<div class="fruit">
    <div class="fruit-img">

    </div>

    <div class="fruit-info">
        <div class="fruit-name">
            <h4>Name: </h4>
            <p><%= item.name %></p>
        </div>

        <div class="fruit-price">
            <h4>Price: </h4>
            <p><%= item.price_per_kilo %></p>
        </div>

        <div class="fruit-kilos">
            <h4>Total kilos available: </h4>
            <p><%= item.quantity %></p>
        </div>

        <div class="fruit-farmer-name">
            <h4>Farmer Name: </h4>
            <p><%= Farmer.find(item.farmer_id).name %></p>
        </div>

        <div id="fruit-add0" class="fruit-add">
            <button class="fruit-add-btn">Add to cart</button>
        </div>

        <%= form_with url: cart_item_index_path, id: "fruit-add-form0", class: "fruit-add-form" do |form| %>
            <%= form.hidden_field :itemid, value: item.id %>
            <%= form.hidden_field :buyerid, value: @current_user_id %>
            <%= form.number_field :quantity, placeholder: "Quantity" %>
            <%= form.submit "Add" %>
        <% end %>
    </div>
</div>

app/views/cart_item/_buy_seed.html.erb
<div class="seed">
    <div class="seed-img">

    </div>

    <div class="seed-info">
        <div class="seed-name">
            <h4>Name: </h4>
            <p><%= item.name %></p>
        </div>

        <div class="seed-price">
            <h4>Price: </h4>
            <p><%= item.price_per_kilo %></p>
        </div>

        <div class="seed-kilos">
            <h4>Total kilos available: </h4>
            <p><%= item.quantity %></p>
        </div>

        <div class="seed-farmer-name">
            <h4>Farmer Name: </h4>
            <p><%= Farmer.find(item.farmer_id).name %></p>
        </div>

        <div id="seed-add0" class="seed-add">
            <button class="seed-add-btn">Add to cart</button>
        </div>

        <%= form_with url: cart_item_index_path, id: "seed-add-form0", class: "seed-add-form" do |form| %>
            <%= form.hidden_field :itemid, value: item.id %>
            <%= form.hidden_field :buyerid, value: @current_user_id %>
            <%= form.number_field :quantity, placeholder: "Quantity" %>
            <%= form.submit "Add" %>
        <% end %>
    </div>
</div>

app/views/cart_item/_buy_vegetable.html.erb
<div class="vegetable">
    <div class="vegetable-img">

    </div>

    <div class="vegetable-info">
        <div class="vegetable-name">
            <h4>Name: </h4>
            <p><%= item.name %></p>
        </div>

        <div class="vegetable-price">
            <h4>Price: </h4>
            <p><%= item.price_per_kilo %></p>
        </div>

        <div class="vegetable-kilos">
            <h4>Total kilos available: </h4>
            <p><%= item.quantity %></p>
        </div>

        <div class="vegetable-farmer-name">
            <h4>Farmer Name: </h4>
            <p><%= Farmer.find(item.farmer_id).name %> </p>
        </div>

        <div id=<%= "vegetable-add0" %> class="vegetable-add">
            <button class="vegetable-add-btn">Add to cart</button>
        </div>

        <%= form_with url: cart_item_index_path, id: "vegetable-add-form0", class: "vegetable-add-form" do |form| %>
            <%= form.hidden_field :itemid, value: item.id %>
            <%= form.hidden_field :buyerid, value: @current_user_id %>
            <%= form.number_field :quantity, placeholder: "Quantity" %>
            <%= form.submit "Add" %>
        <% end %>
    </div>
</div>

app/views/cart_item/_item.html.erb
<div class="item">
    <div class="item-img">

    </div>

    <div class="item-info">
        <div class="item-name">
            <h4>Name: </h4>
            <p><%= Item.find(item.item_id).name %></p>
        </div>

        <div class="item-price">
            <h4>Price: </h4>
            <p><%= Item.find(item.item_id).price_per_kilo %></p>
        </div>

        <div class="item-kilos">
            <h4>Kilos purchased: </h4>
            <p><%= item.quantity %></p>
        </div>

        <div class="item-farmer-name">
            <h4>Farmer Name: </h4>
            <p><%= Buyer.find(item.buyer_id).name %></p>
        </div>

        <%= form_with url: cart_item_index_path, id: "seed-add-form0", class: "seed-add-form" do |form| %>
            <%= form.hidden_field :itemid, value: item.id %>
            <%= form.hidden_field :buyerid, value: @current_user_id %>
            <%= form.number_field :quantity, placeholder: "Quantity" %>
            <%= form.submit "Add" %>
        <% end %>

        <div class="remove-item">
            <button class="item-remove-btn">Remove</button>
        </div>
    </div>
</div>

app/views/cart_item/buy_fruits.html.erb
<div class="buy-fruits">
    <div class="search-container">
      <h2>Fruits</h2>
      <%= form_with url: "/buy_fruits/search" do |form| %>
        <%= form.hidden_field :itemtype, value: "Fruit" %>
        <%= form.text_field :item_name, placeholder: "Fruit name" %>
        <%= form.text_field :farmer_name, placeholder: "Farmer name" %>
        <%= form.submit "Search" %>
      <% end %>
    </div>

    <div class="fruit-result-container">
      <h3>Search Results</h3>
      <div class="fruit-result">
        <% for item in @items %>
          <%= render partial: "buy_fruit", locals: {
            item: item
          } %>
        <% end %>
      </div>
    </div>
</div>

<script src="buy.js"></script>

app/views/cart_item/buy_seeds.html.erb
<div class="buy-seeds">
    <div class="search-container">
      <h2>Seeds</h2>
      <%= form_with url: "/buy_seeds/search" do |form| %>
        <%= form.hidden_field :itemtype, value: "Seed" %>
        <%= form.text_field :item_name, placeholder: "Seed name" %>
        <%= form.text_field :farmer_name, placeholder: "Farmer name" %>
        <%= form.submit "Search" %>
      <% end %>
    </div>

    <div class="seed-result-container">
      <h3>Search Results</h3>
      <div class="seed-result">

        <% for item in @items %>
          <%= render partial: "buy_seed", locals: {
            item: item
          } %>
        <% end %>

      </div>
    </div>
</div>

<script src="buy.js"></script>

app/views/cart_item/buy_vegetables.html.erb
<div class="buy-vegetables">
    <div class="search-container">
      <h2>Vegetables</h2>
      <%= form_with url: "/buy_vegetables/search" do |form| %>
        <%= form.hidden_field :itemtype, value: "Vegetable" %>
        <%= form.text_field :item_name, placeholder: "Vegetable name" %>
        <%= form.text_field :farmer_name, placeholder: "Farmer name" %>
        <%= form.submit "Search" %>
      <% end %>
    </div>

    <div class="vegetable-result-container">
      <h3>Search Results</h3>
      <div class="vegetable-result">
        <% for item in @items %>
          <%= render partial: "buy_vegetable", locals: {
            item: item
          } %>
        <% end %>
      </div>
    </div>
</div>

app/views/cart_item/index.html.erb
<div class="cart">
    <h2>Your cart</h2>
    <div class="cart-items-container">
      <div class="items">
        <% for item in @items%>
          <%= render partial: "item" , locals: {
            item: item
          } %>
        <% end %>
      </div>
    </div>
</div>

<script src="buy.js"></script>

app/views/farmers/_item.html.erb
<div class="item">
    <div class="item-img">

    </div>
    <div class="item-info">
        <div class="item-name">
            <%= item.name %>
        </div>
        <div class="item-quantity">
            <h3>Quantity</h3>
            <p><%= item.quantity %>kg</p>
        </div>
        <div class="item-price">
            <h3>Price</h3>
            <p><%= item.price_per_kilo %>Rs.</p>
        </div>
    </div>
</div>

app/views/farmers/_items.html.erb
<div class="items">
    <div class="items-heading">
        <h3><%= heading %>s</h3>
        <a href="#">View more</a>
    </div>
    <div class="main-items">
        <% for item in items %>
            <%= render partial: "item", locals: {
                item: item
            } %>
        <% end %>
    </div>
</div>

app/views/farmers/index.html.erb
<div class="farmer-dashboard">
    <div class="farmer-info">
      <div class="name">
        <h2><%= @farmer.name %></h2>
      </div>
    </div>

    <div class="items-container">
      <% if @vegetableCount + @fruitCount + @seedCount == 0 %>
        <div class="no-items">
          <img src="items.png" />
          <p>No items available</p>
        </div>
      <% else %>
        <% if @vegetableCount > 0 %>
          <%= render partial: "items", locals: {
            heading: "Vegetable",
            items: @vegetables
          } %>
        <% end %>

        <% if @fruitCount > 0 %>
          <%= render partial: "items", locals: {
            heading: "Fruit",
            items: @fruits
          } %>
        <% end %>

        <% if @seedCount > 0 %>
          <%= render partial: "items", locals: {
            heading: "Seed",
            items: @seeds
          } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/farmers/new.html.erb
<div class = "signin-signup farmer-forms">
  <div class = "form">
    <div class = "sign-up-form">
      <h3> Sign up </h3>
      <%= form_with url: farmers_path do |form| %>
        <div class = "signup-field">
          <%= form.label :name, "Name" %>
          <%= form.text_field :name %>
        </div>
        
        <div class = "signup-field">
          <%= form.label :email, "Email" %>
          <%= form.email_field :email %>
        </div>

        <div class = "signup-field">
          <%= form.label :password, "Password" %>
          <%= form.password_field :password %>
        </div>
        
        <div class = "signup-field">
          <%= form.label :phone, "Phone No." %>
          <%= form.number_field :phone %>
        </div>

        <div class = "signup-field">
          <%= form.submit "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class = "signin-other">
    <div class = "form">
      <div class = "sign-in-form">
        <h3> Sign in </h3>
        <%= form_with url: sessions_path do |form| %>
          <%= form.hidden_field :user, :value => "Farmer"%>

          <div class = "signin-field">
            <label> Email </label>
            <%= form.email_field :email %>
          </div>
      
          <div class = "signin-field">
            <label> Password </label>
            <%= form.password_field :password %>
          </div>
          
          <div class = "signin-field">
            <%= form.submit "Sign in", class: "form-submit" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class = "other-form">
      <%= link_to "Sign up or sign in as buyer", new_buyer_path %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class = "home">
  <div class = "first-section" id = "first-section">
    <div class = "inside-first-section">
      <div class = "up-section">
        <div class = "navbar">
          <div class = "logo-img">
            <%= image_tag "image.png" %>
          </div>

          <div class = "navbar-links">
            <a href = "#"> Home </a>
            <%= link_to "Buy Vegetables", vegetable_buy_path %>
            <%= link_to "Buy Fruits", fruits_buy_path %>
            <%= link_to "Buy Seeds", seeds_buy_path %>
            <% if @current_user != nil %>
              <%= link_to "Log out", destroy_session_path, :method => :delete %>
            <% end %>
          </div>
        </div>
      </div>
      <div class = "down-section">
        <div class = "information">
          <div>
            <div>
              <p> We bring nature to you </p>
            </div>
            <div class = "signup-signin-btn">
              <%= link_to "Sign up or sign in as farmer", signup_signin_farmer_path %> <br/>
              <%= link_to "Sign up or sign in as buyer", signup_signin_buyer_path %>
            </div>
          </div>
        </div>

        <div class = "images">
      </div>

      </div>
    </div>
  </div>

  <div class = "process">
    <h2> How this works </h2>
    <div class = "main-process">
      <div class = "step">
        <div class = "step-image">
          <%= image_tag "step-one.jpg" %>
        </div>

        <div class = "step-desc">
          <p> Farmers create their profile and post products that they want to sell. </p>
        </div>
      </div>
      
      <div class = "step">
        <div class = "step-desc">
          <p> Buyers create their profile and place orders for products that they want to buy. </p>
        </div>
        
        <div class = "step-image">
          <%= image_tag "step-two.png" %>
        </div>
      </div>
      
      <div class = "step">
        <div class = "step-image">
          <%= image_tag "step-three.jpg" %>
        </div>

        <div class = "step-desc">
          <p> Our delivery team collect products from farmers and delivers them to respective buyers.
           </p>
        </div>
      </div>
    </div>
  </div>

  <div class = "get-started">
    <%= link_to "Get Started", "#firstsection" %>
  </div>

  <div class = "footer">

  </div>
</div>

app/views/items/new.html.erb
<div class="add-item">
    <h2>
        Add item
    </h2>

    <%= form_with url: items_path do |form| %>
        <div class="form-field">
            <%= form.label :name, "Name" %>
            <%= form.text_field :name %>
        </div>

        <div class="form-field">
            <%= form.label :itemtype, "Item type" %>
            <%= form.select :itemtype, ["Vegetable", "Fruit", "Seed"] %>
        </div>

        <div class="form-field">
            <%= form.label :quantity, "Quantity" %>
            <%= form.number_field :quantity %>
        </div>

        <div class="form-field">
            <%= form.label :price_per_kilo, "Price per kilo" %>
            <%= form.number_field :price_per_kilo %>
        </div>

        <div class="form-field">
            <%= form.submit "Add item" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Krishi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Didact+Gothic&family=Exo:wght@500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @page != "Home" && @page != "New buyer" && @page != "New farmer" %>
      <% if @current_user == nil %>
        <div class = "navbar">
          <div class = "logo-img">
            <%= image_tag "image.png" %>
          </div>

          <div class = "navbar-links">
            <%= link_to "Home", "/" %>
            <%= link_to "Buy Vegetables", vegetable_buy_path %>
            <%= link_to "Buy Fruits", fruits_buy_path %>
            <%= link_to "Buy Seeds", seeds_buy_path %>
          </div>
        </div>

      <% else %>
        <% if @usertype == "farmer" %>
          <div class = "navbar">
            <div class = "logo-img">
              <%= image_tag "image.png" %>
            </div>

            <div class = "navbar-links">
              <%= link_to "Home", farmers_path %>
              <%= link_to "New item", "/" %>
              <%= link_to "Edit items", "/" %>
              <%= link_to "Delete items", "/" %>
              <%= link_to "Log out", destroy_session_path, :method => :delete %>
            </div>
          </div>

        <% else %>
          <div class = "navbar">
            <div class = "logo-img">
              <%= image_tag "image.png" %>
            </div>

            <div class = "navbar-links">
            <%= link_to "Home", buyers_path %>
              <%= link_to "Buy Vegetables", "buy_vegetables/" %>
              <%= link_to "Buy Fruits", "buy_fruits/" %>
              <%= link_to "Buy Seeds", "buy_seeds/" %>
              <%= link_to "Cart", cart_item_index_path %>
              <%= link_to "Log out", destroy_session_path, :method => :delete %>
            </div>
          </div>

        <% end %>
      <% end %>
    <% end %>


    <%= yield %>
  </body>
</html>